### ISSUE TITLE
Is this method secure?

### ISSUE THREAD

**Issue by KiloKilo7** [Fuchs/jira-remote-user-sso#2]
I am rather new to all this. BUT I was able to implement your plugin for kerberos authentication to JIRA. Works very well, thank you!  It is probably just my ignorance, but your plugin seems to simply check the x-forward-user value and then login the user into JIRA. What would stop Jira authenticating any request that had an x-forward-user? Shouldn't the plugin also capture the kerberos ticket and validate back to the KDC or apache server? Or is it sufficient to restrict the Jira tomcat server to only accept requests from the apache server?

**Comment by Fuchs** [comment]
Hi, as pointed out in the readme:  "For security reasons you should make sure that user-set headers are removed, otherwise users will be able to spoof authentication and log in as a different user!"

This obviously also means that JIRA should only be available through whichever httpd you put in front, otherwise users can simply send spoofed requests. 

Implementing (parts of) kerberos functionality in the plugin would make it a lot more complicated but, on the other hand, indeed remove the need of a httpd in front of it. 

If you configure tomcat / your server to only listen to requests from Apache's httpd and configure it as described in the readme it should be secure, as user spoofed headers won't make it through and the only way to set x-forward-user should be via Apache's httpd.

Feel free to create a plugin which implements kerberos itself, I'm pretty sure that there even are java libraries available for that.

Kind regards, 

Christian
